### PR TITLE
Update to SDL2

### PR DESCRIPTION
**Pull request by moleculext**
I've tried to update the SDL version from 1.2 to 2.0.

Graphics, sound and keyboard are ok. Please remove the config file (usually in~/.config/emilia) to avoid issue with keyboard.

The only issue I've noticed is lack of re-draw when changing the screen resolution in the graphic menu.

### CODE REVIEW

**Comment by sergiomb2** [comment]
hum can you rebase your repo with master of this and use git push --force

**Comment by moleculext** [comment]
Done!

**Comment by sergiomb2** [comment]
Nice ! , I going open one devel branch and merge this to devel branch with other 2 PRs and I test it before merge to master if works correctly etc 
Thanks!

**Comment by sergiomb2** [comment]
I have delete iii  commit from master branch with git pull --force ... but it keeps appearing in your fork ...

**Comment by sergiomb2** [comment]
merged to devel , you have to delete iii commit ! , 
git rebase  -i HEAD~6
delete the commit "iii", save and git push --force , sorry that commit went wrong to git master , a long time ago ...

**Comment by sergiomb2** [comment]
I reorder commits again , now  https://github.com/sergiomb2/pinball/commits/devel is in chronology order.  I also delete some old branches . 
Going to test now.

**Pull request closed without merging**
