### PR TITLE
My table

### PR DESCRIPTION
**Pull request by paolo-caroni**
upgrade all my data, removed old hurd table.

### CODE REVIEW

**Comment by sergiomb2** [comment]
Professor2 table have improvements, I will add for sure, but hurd, in my personal opinion I prefer gray version, is more clean. the rest are equal except music I prefer gray music version and 

```
  object floorleftup {
-  0 0 0
+  0.0476189 0 0
```

professor2 textures IMHO should be more flat ... , like professor original ...

many thanks !

**Comment by paolo-caroni** [comment]
I have re-added old gray version.
The hurd red color can create optical problem with red ball I know.
Consider you free to change all you want. Is free software (add your name on README and what you change).

IMHO the most important package to maintain on EmiliaPinballProject is pinedit, without it is impossible create new table.
This is the source https://sourceforge.net/p/pinball/pinedit/ci/master/tree/
@rzr start to translate Qt3 on new Qt4.

**Comment by rzr** [comment]
Hi good to know you're still on it
IMHO the most important is to be able to packages extra tables without rebuildiing pinball

**Comment by sergiomb2** [comment]
Hello, @rzr I just add https://github.com/sergiomb2/pinball/blob/master/License.txt , can we jump "be able to packages extra tables without rebuildiing pinball" ? 
I have to go now , but I reply to the other questions later.

Many thanks.

**Comment by rzr** [comment]
the problem is not only legal, but there is no reason to rebuild pinball for adding extra tables

didnt you manage to build using pinconfig ?

**Comment by sergiomb2** [comment]
well also there is no reason to have 2 projects .

> didnt you manage to build using pinconfig ?

no , what is pinconfig ?

**Comment by sergiomb2** [comment]
> IMHO the most important package to maintain on EmiliaPinballProject is pinedit, without it is impossible create new table.

I also put pinedit in github https://github.com/sergiomb2/pinball-pinedit  
I had merged qt4 https://github.com/sergiomb2/pinball-pinedit/commits/master 
he state of the art is : https://github.com/sergiomb2/pinball.old/issues/2#issuecomment-181045773 

I may try update pinball to SDL2 , for me it is the biggest goal , to project survive , else will stay in very old SDL1 which will be deprecated soon. Also we already have one attempt where https://github.com/NickolasJShoemaker/pinball/commit/49417965237e87d2246192082a97b87ff18b5664

**Comment by sergiomb2** [comment]
> Add old gray version

Cool equals the master , so all your work is merged, many thanks, I may opt out by gray version and delete red version and do a new branch and refactor of all patches ... , in my https://github.com/sergiomb2/pinball.old I already got 4 starts and some work , but I prefer do a fork of rzrof and reload my project pinball , we can't modify one source project to one fork project , I may have the same problem with pinedit ...

Cheers

**Comment by rzr** [comment]
IICR pinconfig  was an autotools file to build and link to pinball libs without rebuilding it. if you fix it this mean you can upgrade your table without rebuilding the whole project.

**Comment by orbea** [comment]
@sergiomb2 Hi, I've just found this newer repo for pinball and noticed your main goal is for this project to survive. Have you thought about porting it to libretro? It would probably be a good way for it to both reach more users and ensure its survival. Additionally after the initial work it would reduce the burden on maintaining anything other than the engine and tables when others are already actively maintaining the RetroArch frontend.

**Comment by sergiomb2** [comment]
>  Have you thought about porting it to libretro?

at least I want update to SDL2 , libretro https://www.libretro.com/ and  Vulkan are pretty new ...

**Comment by orbea** [comment]
Just so its clear, the vulkan development in RetroArch / Libretro is new. They of course have many software and some opengl cores.

**Comment by sergiomb2** [comment]
FTR diff of the project hurd is equal to paolo repo data/hurd.gray/ [1]
and hurd.old is the same of paolo repo data/hurd.red [2]
So I'm closing this PR ( as merged)

[1]
diff pinball.github/data/hurd pinball.paolo/data/hurd.gray/
[2]
diff pinball.github/data/hurd.old/ pinball.paolo/data/hurd.red/ -up
diff -up pinball.github/data/hurd.old/pinball.pbl pinball.paolo/data/hurd.red/pinball.pbl

--- pinball.github/data/hurd.old/pinball.pbl    2016-11-19 03:33:45.255305516 +0000
+++ pinball.paolo/data/hurd.red/pinball.pbl     2016-11-20 18:14:26.941408228 +0000
@@ -63363,7 +63363,7 @@ object out_table {
     vts { 24 }
     pls { 20 }
     tex { 
-      wood.jpg
+      Wood.jpg
     }
     vtx { 
       -103.8 -30 -59.4

**Comment by sergiomb2** [comment]
FTR  diff of the project hurd  is equal to paolo repo data/hurd.gray/ [1]
and hurd.old is the same of paolo repo data/hurd.red [2]
So I'm closing  this PR  ( as merged) 

[1]
diff pinball.github/data/hurd pinball.paolo/data/hurd.gray/
[2]  
diff pinball.github/data/hurd.old/ pinball.paolo/data/hurd.red/ -up 
diff -up pinball.github/data/hurd.old/pinball.pbl pinball.paolo/data/hurd.red/pinball.pbl
```
--- pinball.github/data/hurd.old/pinball.pbl    2016-11-19 03:33:45.255305516 +0000
+++ pinball.paolo/data/hurd.red/pinball.pbl     2016-11-20 18:14:26.941408228 +0000
@@ -63363,7 +63363,7 @@ object out_table {
     vts { 24 }
     pls { 20 }
     tex { 
-      wood.jpg
+      Wood.jpg
     }
     vtx { 
       -103.8 -30 -59.4

```

**Pull request closed without merging**
