### PR TITLE
Update On-Screen Messages with Settings

### PR DESCRIPTION
**Pull request by c30zD**
This fixes an issue with the on-screen messages for reset and ball launch, which weren't updated even though the settings for them were modified. There is also a fix for the reset functionality, which was hard-coded to letter "R", instead of using the user's settings.

The German localization files have been updated, but I haven't tested them. I did modify one of the files manually because some strings were missing after the automatic update.

There is an issue that, even though it's unlikely to be seen, it's still there: for example, the message that says something like "press return to launch ball", once rendered, if the user wishes to change its value and then returns to the game, then the message will still be the same until it is rendered again (i.e. after a reset). This also happens with the reset message. I don't think it's necessary to change this, because most people would not stop the game to change the settings to launch the ball or reset the game just after they see them, but it's worth noting that the issue is there and it would be a good idea to fix it in the future. However, I'm not planning to work on it any time soon.

### CODE REVIEW

**Comment by sergiomb2** [comment]
merged ! , I chery-pick the 4 commits , please rebase your branch with mine , before  do a pull request . 
I hope now git go straight ahead

**Comment by c30zD** [comment]
Will do next time! :) but it seems to me a bit odd because I merged the branch with a local copy of your devel branch (`git merge message_sync`) to test it before making the pull request and I didn't have any problems. Are you sure cherry-picking was necessary?

**Comment by sergiomb2** [comment]
take a look in https://github.com/sergiomb2/pinball/network , I want do merges with fast forward.
So I suggest , you delete you fork and do one new fork.
I had done git push --force myself , so my tree is not the same of 6 months ago ...

**Comment by c30zD** [comment]
I'll keep it in mind for the future, although as you suggested earlier, a `git rebase` (or maybe better a `git reset`) might work as well.

I understand if you want to keep it simple with fast-forwarding, but if this is because of that "iii" commit you deleted some time ago (which happened before another commit with the License.txt file), I'm aware that you changed your history: I noticed it when I wanted to check my first pull request and saw some comments that had nothing to do with it, so I did a `git rebase` to match your history back then. If it's something else, please explain.

I re-did the merge (because I had deleted the branch) and pushed it to show you the changes on the network. Even though the merge required the recursive strategy, it seems pretty straight-forward. You do have a point in that I should have merged upstream changes in advance into my fork, but because of the test, I didn't think it would be a problem. Check it out: https://github.com/sergiomb2/pinball/network (I did `git checkout -b upstream_devel_test 70d287fcdd0912fe81ccee4c18f1b87fbc9cf881 && git merge message_sync`, where the commit is the last one in devel before applying my commits)

**Comment by sergiomb2** [comment]
> I'll keep it in mind for the future, although as you suggested earlier, a git rebase (or maybe better a git reset) might work as well.
> 
> I understand if you want to keep it simple with fast-forwarding, but if this is because of that "iii" commit you deleted some time ago (which happened before another commit with the License.txt file), I'm aware that you changed your history: I noticed it when I wanted to check my first pull request and saw some comments that had nothing to do with it, so I did a git rebase to match your history back then. If it's something else, please explain.

no , that is it , yes something like:  git reset upstream --hard 


> I re-did the merge (because I had deleted the branch) and pushed it to show you the changes on the network. Even though the merge required the recursive strategy, it seems pretty straight-forward. You do have a point in that I should have merged upstream changes in advance into my fork, but because of the test, I didn't think it would be a problem. Check it out: https://github.com/sergiomb2/pinball/network (I did git checkout -b upstream_devel_test 70d287fcdd0912fe81ccee4c18f1b87fbc9cf881 && git merge message_sync, where the commit is the last one in devel before applying my commits)

I didn't understand all that you did write here but for some reason "the merge commit" give me problems, we may rebase commits before ask for a pull request , I'd like do git merge with fast forward , just because IMHO we can read the code and evolution better , just it . Also for example , just to read better , we may squash the first 3 commits ... 

From now on, I hope not delete any commit from master history at least , and maybe also do the same in devel repo history 

Thanks for your work

**Comment by c30zD** [comment]
> I didn't understand all that you did write here but for some reason "the merge commit" give me problems, we may rebase commits before ask for a pull request , I'd like do git merge with fast forward , just because IMHO we can read the code and evolution better , just it . Also for example , just to read better , we may squash the first 3 commits ...

What I meant with my last paragraph was that `upstream_devel_test` is a new branch (not the one I used before the pull request, which I deleted) and it didn't use fast-forward merge, but it doesn't change the history to such a point that it becomes a nightmare.

For future pull requests, I'll try to make them fast-forward merges. Regarding code history, it's true that it becomes easier to read that way, although I like to use `git log --graph --decorate --oneline --all` so I guess it doesn't bother me that much; with a good merge message it should be clear the evolution, anyway (something I admit I didn't do very well).

> Thanks for your work

You're welcome :)

PS: I don't know why the merge commit didn't work. Did you also test the code after cherry-picking? Does the problem persist then? And, what is the problem exactly? Did you remember to test in a clean working state (`make clean && ./clean` after stashing any other work)?

**Comment by sergiomb2** [comment]
> PS: I don't know why the merge commit didn't work. Did you also test the code after cherry-picking? Does the problem persist then? And, what is the problem exactly? Did you remember to test in a clean working state (make clean && ./clean after stashing any other work)?

I didn't test it yet , I said I got a problem on git merge and only when I tried merge your repo .
I redo your commits again , IMHO one commit should meaningful and have all pieces together, so I reduce your work into 3 commits, I put "Add modification notices" in same commit of the modifications ...

So yes  you will need git reset upstream --hard again ,

https://github.com/sergiomb2/pinball/commit/a76d9cf6c80519ca6efb9e1e98c319ea712d9c5d
https://github.com/sergiomb2/pinball/commit/8057384cf476617fdc3b110d7755bb85a03c19f8
https://github.com/sergiomb2/pinball/commit/1f16f06037ddd8ad0cc5300ece5ccca76df4b746

**Pull request closed without merging**
