### PR TITLE
The tables professor and professor2 are unplayable for now

### PR DESCRIPTION
**Pull request by zezinho42**
The professor* tables seem never finished projects : 
- Both are very similar
- Graphics are "raw"
- Sometimes the ball keeps locked in the table

So let's not suggest them with the random table selection.

### CODE REVIEW

**Comment by sergiomb2** [comment]
negative acknowledgement

we need move good graphics from professor to professor 2 , one is the original table other is a new table

**Comment by zezinho42** [comment]
I must have missed something : is there any differences other than graphics between the two tables?

Anymay, the idea was just to not give them with the random sort, as they have much lower quality than the others, and still keep them selectable manually.

**Comment by sergiomb2** [comment]
> I must have missed something : is there any differences other than graphics between the two tables?

yes , second table have more things

**Comment by sergiomb2** [comment]
NACK , both tables works we just need merge then

**Pull request closed without merging**
