### PR TITLE
Drop Allegro Support.

### PR DESCRIPTION
**Pull request by moleculext**
As we are migrating to SDL2, I propose to drop support of Allegro.

This patch removes the EM_USE_ALLEGRO flag with associated code, and also remove the EM_USE_SDL flag that becomes useless.

The way allegro and SDL are both in the code is really ugly (#ifdef everywhere), and it makes the code hard to read and maintain.
By the way, if Allegro support is still required I would propose a cleaner pattern with interfaces and factories.

### CODE REVIEW

**Comment by sergiomb2** [comment]
Hello , I agree with "The way allegro and SDL are both in the code is really ugly (#ifdef everywhere), and it makes the code hard to read and maintain" 
To tell you a little of the story , I think allegro was introduced to support meego , with rzr (I guess) , I take a look of progress of allegro and we got allegro5 but no game that is built with it .
If you think is the best way , I will merge it ! ok ?

**Comment by moleculext** [comment]
Hi,
I can read that Meego has been [terminated in favor of Tizen](https://en.wikipedia.org/wiki/MeeGo). Should we ask @rzr if Allegro support is still needed?

**Comment by rzr** [comment]
it can dropped yes , btw ask me any tips about tizen if someone consider to port to it or wayland based systems

**Comment by moleculext** [comment]
@rzr Thanks a lot for your quick answer!

**Pull request merged**
